CanvasRenderingContext2D = function CanvasRenderingContext2D(){box.throwError("TypeError", "Illegal constructor") }
box.func_set_fake_toString(CanvasRenderingContext2D)
box.rename(CanvasRenderingContext2D.prototype, "CanvasRenderingContext2D")


box.defineProperty(CanvasRenderingContext2D, 'length', 0, true, false, false);
box.defineProperty(CanvasRenderingContext2D, 'name', 'CanvasRenderingContext2D', true, false, false);
box.defineProperty(CanvasRenderingContext2D, 'arguments', null, false, false, false);
box.defineProperty(CanvasRenderingContext2D, 'caller', null, false, false, false);


box.defineProperty(CanvasRenderingContext2D.prototype, 'canvas', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["canvas"].get, "get canvas");
box.defineProperty(CanvasRenderingContext2D.prototype, 'globalAlpha', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalAlpha"].get, "get globalAlpha");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalAlpha"].set, "set globalAlpha");
box.defineProperty(CanvasRenderingContext2D.prototype, 'globalCompositeOperation', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalCompositeOperation"].get, "get globalCompositeOperation");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["globalCompositeOperation"].set, "set globalCompositeOperation");
box.defineProperty(CanvasRenderingContext2D.prototype, 'filter', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["filter"].get, "get filter");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["filter"].set, "set filter");
box.defineProperty(CanvasRenderingContext2D.prototype, 'imageSmoothingEnabled', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingEnabled"].get, "get imageSmoothingEnabled");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingEnabled"].set, "set imageSmoothingEnabled");
box.defineProperty(CanvasRenderingContext2D.prototype, 'imageSmoothingQuality', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingQuality"].get, "get imageSmoothingQuality");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["imageSmoothingQuality"].set, "set imageSmoothingQuality");
box.defineProperty(CanvasRenderingContext2D.prototype, 'strokeStyle', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["strokeStyle"].get, "get strokeStyle");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["strokeStyle"].set, "set strokeStyle");
box.defineProperty(CanvasRenderingContext2D.prototype, 'fillStyle', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fillStyle"].get, "get fillStyle");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fillStyle"].set, "set fillStyle");
box.defineProperty(CanvasRenderingContext2D.prototype, 'shadowOffsetX', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetX"].get, "get shadowOffsetX");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetX"].set, "set shadowOffsetX");
box.defineProperty(CanvasRenderingContext2D.prototype, 'shadowOffsetY', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetY"].get, "get shadowOffsetY");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowOffsetY"].set, "set shadowOffsetY");
box.defineProperty(CanvasRenderingContext2D.prototype, 'shadowBlur', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowBlur"].get, "get shadowBlur");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowBlur"].set, "set shadowBlur");
box.defineProperty(CanvasRenderingContext2D.prototype, 'shadowColor', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowColor"].get, "get shadowColor");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["shadowColor"].set, "set shadowColor");
box.defineProperty(CanvasRenderingContext2D.prototype, 'lineWidth', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineWidth"].get, "get lineWidth");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineWidth"].set, "set lineWidth");
box.defineProperty(CanvasRenderingContext2D.prototype, 'lineCap', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineCap"].get, "get lineCap");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineCap"].set, "set lineCap");
box.defineProperty(CanvasRenderingContext2D.prototype, 'lineJoin', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineJoin"].get, "get lineJoin");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineJoin"].set, "set lineJoin");
box.defineProperty(CanvasRenderingContext2D.prototype, 'miterLimit', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["miterLimit"].get, "get miterLimit");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["miterLimit"].set, "set miterLimit");
box.defineProperty(CanvasRenderingContext2D.prototype, 'lineDashOffset', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineDashOffset"].get, "get lineDashOffset");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["lineDashOffset"].set, "set lineDashOffset");
box.defineProperty(CanvasRenderingContext2D.prototype, 'font', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["font"].get, "get font");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["font"].set, "set font");
box.defineProperty(CanvasRenderingContext2D.prototype, 'textAlign', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textAlign"].get, "get textAlign");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textAlign"].set, "set textAlign");
box.defineProperty(CanvasRenderingContext2D.prototype, 'textBaseline', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textBaseline"].get, "get textBaseline");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textBaseline"].set, "set textBaseline");
box.defineProperty(CanvasRenderingContext2D.prototype, 'direction', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["direction"].get, "get direction");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["direction"].set, "set direction");
box.defineProperty(CanvasRenderingContext2D.prototype, 'fontKerning', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontKerning"].get, "get fontKerning");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontKerning"].set, "set fontKerning");
box.defineProperty(CanvasRenderingContext2D.prototype, 'fontStretch', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontStretch"].get, "get fontStretch");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontStretch"].set, "set fontStretch");
box.defineProperty(CanvasRenderingContext2D.prototype, 'fontVariantCaps', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontVariantCaps"].get, "get fontVariantCaps");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["fontVariantCaps"].set, "set fontVariantCaps");
box.defineProperty(CanvasRenderingContext2D.prototype, 'letterSpacing', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["letterSpacing"].get, "get letterSpacing");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["letterSpacing"].set, "set letterSpacing");
box.defineProperty(CanvasRenderingContext2D.prototype, 'textRendering', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textRendering"].get, "get textRendering");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["textRendering"].set, "set textRendering");
box.defineProperty(CanvasRenderingContext2D.prototype, 'wordSpacing', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["wordSpacing"].get, "get wordSpacing");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(CanvasRenderingContext2D.prototype)["wordSpacing"].set, "set wordSpacing");
box.defineProperty(CanvasRenderingContext2D.prototype, 'clip', function clip(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.clip)
box.defineProperty(CanvasRenderingContext2D.prototype, 'createConicGradient', function createConicGradient(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.createConicGradient)
box.defineProperty(CanvasRenderingContext2D.prototype, 'createImageData', function createImageData(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.createImageData)
box.defineProperty(CanvasRenderingContext2D.prototype, 'createLinearGradient', function createLinearGradient(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.createLinearGradient)
box.defineProperty(CanvasRenderingContext2D.prototype, 'createPattern', function createPattern(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.createPattern)
box.defineProperty(CanvasRenderingContext2D.prototype, 'createRadialGradient', function createRadialGradient(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.createRadialGradient)
box.defineProperty(CanvasRenderingContext2D.prototype, 'drawFocusIfNeeded', function drawFocusIfNeeded(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.drawFocusIfNeeded)
box.defineProperty(CanvasRenderingContext2D.prototype, 'drawImage', function drawImage(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.drawImage)
box.defineProperty(CanvasRenderingContext2D.prototype, 'fill', function fill(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.fill)
box.defineProperty(CanvasRenderingContext2D.prototype, 'fillText', function fillText(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.fillText)
box.defineProperty(CanvasRenderingContext2D.prototype, 'getContextAttributes', function getContextAttributes(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.getContextAttributes)
box.defineProperty(CanvasRenderingContext2D.prototype, 'getImageData', function getImageData(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.getImageData)
box.defineProperty(CanvasRenderingContext2D.prototype, 'getLineDash', function getLineDash(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.getLineDash)
box.defineProperty(CanvasRenderingContext2D.prototype, 'getTransform', function getTransform(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.getTransform)
box.defineProperty(CanvasRenderingContext2D.prototype, 'isContextLost', function isContextLost(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.isContextLost)
box.defineProperty(CanvasRenderingContext2D.prototype, 'isPointInPath', function isPointInPath(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.isPointInPath)
box.defineProperty(CanvasRenderingContext2D.prototype, 'isPointInStroke', function isPointInStroke(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.isPointInStroke)
box.defineProperty(CanvasRenderingContext2D.prototype, 'measureText', function measureText(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.measureText)
box.defineProperty(CanvasRenderingContext2D.prototype, 'putImageData', function putImageData(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.putImageData)
box.defineProperty(CanvasRenderingContext2D.prototype, 'reset', function reset(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.reset)
box.defineProperty(CanvasRenderingContext2D.prototype, 'roundRect', function roundRect(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.roundRect)
box.defineProperty(CanvasRenderingContext2D.prototype, 'save', function save(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.save)
box.defineProperty(CanvasRenderingContext2D.prototype, 'scale', function scale(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.scale)
box.defineProperty(CanvasRenderingContext2D.prototype, 'setLineDash', function setLineDash(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.setLineDash)
box.defineProperty(CanvasRenderingContext2D.prototype, 'setTransform', function setTransform(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.setTransform)
box.defineProperty(CanvasRenderingContext2D.prototype, 'stroke', function stroke(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.stroke)
box.defineProperty(CanvasRenderingContext2D.prototype, 'strokeText', function strokeText(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.strokeText)
box.defineProperty(CanvasRenderingContext2D.prototype, 'transform', function transform(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.transform)
box.defineProperty(CanvasRenderingContext2D.prototype, 'translate', function translate(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.translate)
box.defineProperty(CanvasRenderingContext2D.prototype, 'arc', function arc(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.arc)
box.defineProperty(CanvasRenderingContext2D.prototype, 'arcTo', function arcTo(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.arcTo)
box.defineProperty(CanvasRenderingContext2D.prototype, 'beginPath', function beginPath(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.beginPath)
box.defineProperty(CanvasRenderingContext2D.prototype, 'bezierCurveTo', function bezierCurveTo(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.bezierCurveTo)
box.defineProperty(CanvasRenderingContext2D.prototype, 'clearRect', function clearRect(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.clearRect)
box.defineProperty(CanvasRenderingContext2D.prototype, 'closePath', function closePath(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.closePath)
box.defineProperty(CanvasRenderingContext2D.prototype, 'ellipse', function ellipse(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.ellipse)
box.defineProperty(CanvasRenderingContext2D.prototype, 'fillRect', function fillRect(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.fillRect)
box.defineProperty(CanvasRenderingContext2D.prototype, 'lineTo', function lineTo(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.lineTo)
box.defineProperty(CanvasRenderingContext2D.prototype, 'moveTo', function moveTo(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.moveTo)
box.defineProperty(CanvasRenderingContext2D.prototype, 'quadraticCurveTo', function quadraticCurveTo(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.quadraticCurveTo)
box.defineProperty(CanvasRenderingContext2D.prototype, 'rect', function rect(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.rect)
box.defineProperty(CanvasRenderingContext2D.prototype, 'resetTransform', function resetTransform(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.resetTransform)
box.defineProperty(CanvasRenderingContext2D.prototype, 'restore', function restore(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.restore)
box.defineProperty(CanvasRenderingContext2D.prototype, 'rotate', function rotate(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.rotate)
box.defineProperty(CanvasRenderingContext2D.prototype, 'strokeRect', function strokeRect(){debugger;}, true, true, true); box.func_set_fake_toString(CanvasRenderingContext2D.prototype.strokeRect)


