Document = function Document(){}
box.func_set_fake_toString(Document)
box.rename(Document.prototype, "Document")

Object.setPrototypeOf(Document.prototype,Node.prototype)

box.defineProperty(Document, 'length', 0, true, false, false);
box.defineProperty(Document, 'name', 'Document', true, false, false);
box.defineProperty(Document, 'arguments', null, false, false, false);
box.defineProperty(Document, 'caller', null, false, false, false);


box.defineProperty(Document.prototype, 'implementation', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["implementation"].get, "get implementation");
box.defineProperty(Document.prototype, 'URL', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["URL"].get, "get URL");
box.defineProperty(Document.prototype, 'documentURI', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["documentURI"].get, "get documentURI");
box.defineProperty(Document.prototype, 'compatMode', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["compatMode"].get, "get compatMode");
box.defineProperty(Document.prototype, 'characterSet', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["characterSet"].get, "get characterSet");
box.defineProperty(Document.prototype, 'charset', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["charset"].get, "get charset");
box.defineProperty(Document.prototype, 'inputEncoding', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["inputEncoding"].get, "get inputEncoding");
box.defineProperty(Document.prototype, 'contentType', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["contentType"].get, "get contentType");
box.defineProperty(Document.prototype, 'doctype', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["doctype"].get, "get doctype");
box.defineProperty(Document.prototype, 'documentElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["documentElement"].get, "get documentElement");
box.defineProperty(Document.prototype, 'xmlEncoding', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["xmlEncoding"].get, "get xmlEncoding");
box.defineProperty(Document.prototype, 'xmlVersion', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["xmlVersion"].get, "get xmlVersion");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["xmlVersion"].set, "set xmlVersion");
box.defineProperty(Document.prototype, 'xmlStandalone', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["xmlStandalone"].get, "get xmlStandalone");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["xmlStandalone"].set, "set xmlStandalone");
box.defineProperty(Document.prototype, 'domain', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["domain"].get, "get domain");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["domain"].set, "set domain");
box.defineProperty(Document.prototype, 'referrer', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["referrer"].get, "get referrer");
box.defineProperty(Document.prototype, 'cookie', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["cookie"].get, "get cookie");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["cookie"].set, "set cookie");
box.defineProperty(Document.prototype, 'lastModified', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["lastModified"].get, "get lastModified");
box.defineProperty(Document.prototype, 'readyState', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["readyState"].get, "get readyState");
box.defineProperty(Document.prototype, 'title', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["title"].get, "get title");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["title"].set, "set title");
box.defineProperty(Document.prototype, 'dir', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["dir"].get, "get dir");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["dir"].set, "set dir");
box.defineProperty(Document.prototype, 'body', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["body"].get, "get body");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["body"].set, "set body");
box.defineProperty(Document.prototype, 'head', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["head"].get, "get head");
box.defineProperty(Document.prototype, 'images', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["images"].get, "get images");
box.defineProperty(Document.prototype, 'embeds', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["embeds"].get, "get embeds");
box.defineProperty(Document.prototype, 'plugins', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["plugins"].get, "get plugins");
box.defineProperty(Document.prototype, 'links', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["links"].get, "get links");
box.defineProperty(Document.prototype, 'forms', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["forms"].get, "get forms");
box.defineProperty(Document.prototype, 'scripts', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["scripts"].get, "get scripts");
box.defineProperty(Document.prototype, 'currentScript', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["currentScript"].get, "get currentScript");
box.defineProperty(Document.prototype, 'defaultView', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["defaultView"].get, "get defaultView");
box.defineProperty(Document.prototype, 'designMode', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["designMode"].get, "get designMode");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["designMode"].set, "set designMode");
box.defineProperty(Document.prototype, 'onreadystatechange', undefined, true, true, undefined, function () {debugger; return 'undefined'}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onreadystatechange"].get, "get onreadystatechange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onreadystatechange"].set, "set onreadystatechange");
box.defineProperty(Document.prototype, 'anchors', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["anchors"].get, "get anchors");
box.defineProperty(Document.prototype, 'applets', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["applets"].get, "get applets");
box.defineProperty(Document.prototype, 'fgColor', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fgColor"].get, "get fgColor");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fgColor"].set, "set fgColor");
box.defineProperty(Document.prototype, 'linkColor', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["linkColor"].get, "get linkColor");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["linkColor"].set, "set linkColor");
box.defineProperty(Document.prototype, 'vlinkColor', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["vlinkColor"].get, "get vlinkColor");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["vlinkColor"].set, "set vlinkColor");
box.defineProperty(Document.prototype, 'alinkColor', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["alinkColor"].get, "get alinkColor");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["alinkColor"].set, "set alinkColor");
box.defineProperty(Document.prototype, 'bgColor', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["bgColor"].get, "get bgColor");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["bgColor"].set, "set bgColor");
box.defineProperty(Document.prototype, 'all', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["all"].get, "get all");
box.defineProperty(Document.prototype, 'scrollingElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["scrollingElement"].get, "get scrollingElement");
box.defineProperty(Document.prototype, 'onpointerlockchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockchange"].get, "get onpointerlockchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockchange"].set, "set onpointerlockchange");
box.defineProperty(Document.prototype, 'onpointerlockerror', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockerror"].get, "get onpointerlockerror");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerlockerror"].set, "set onpointerlockerror");
box.defineProperty(Document.prototype, 'hidden', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["hidden"].get, "get hidden");
box.defineProperty(Document.prototype, 'visibilityState', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["visibilityState"].get, "get visibilityState");
box.defineProperty(Document.prototype, 'wasDiscarded', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["wasDiscarded"].get, "get wasDiscarded");
box.defineProperty(Document.prototype, 'featurePolicy', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["featurePolicy"].get, "get featurePolicy");
box.defineProperty(Document.prototype, 'webkitVisibilityState', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["webkitVisibilityState"].get, "get webkitVisibilityState");
box.defineProperty(Document.prototype, 'webkitHidden', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["webkitHidden"].get, "get webkitHidden");
box.defineProperty(Document.prototype, 'onbeforecopy', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecopy"].get, "get onbeforecopy");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecopy"].set, "set onbeforecopy");
box.defineProperty(Document.prototype, 'onbeforecut', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecut"].get, "get onbeforecut");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforecut"].set, "set onbeforecut");
box.defineProperty(Document.prototype, 'onbeforepaste', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforepaste"].get, "get onbeforepaste");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforepaste"].set, "set onbeforepaste");
box.defineProperty(Document.prototype, 'onfreeze', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfreeze"].get, "get onfreeze");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfreeze"].set, "set onfreeze");
box.defineProperty(Document.prototype, 'onresume', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onresume"].get, "get onresume");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onresume"].set, "set onresume");
box.defineProperty(Document.prototype, 'onsearch', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsearch"].get, "get onsearch");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsearch"].set, "set onsearch");
box.defineProperty(Document.prototype, 'onvisibilitychange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onvisibilitychange"].get, "get onvisibilitychange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onvisibilitychange"].set, "set onvisibilitychange");
box.defineProperty(Document.prototype, 'fullscreenEnabled', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenEnabled"].get, "get fullscreenEnabled");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenEnabled"].set, "set fullscreenEnabled");
box.defineProperty(Document.prototype, 'fullscreen', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreen"].get, "get fullscreen");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreen"].set, "set fullscreen");
box.defineProperty(Document.prototype, 'onfullscreenchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenchange"].get, "get onfullscreenchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenchange"].set, "set onfullscreenchange");
box.defineProperty(Document.prototype, 'onfullscreenerror', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenerror"].get, "get onfullscreenerror");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfullscreenerror"].set, "set onfullscreenerror");
box.defineProperty(Document.prototype, 'webkitIsFullScreen', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["webkitIsFullScreen"].get, "get webkitIsFullScreen");
box.defineProperty(Document.prototype, 'webkitCurrentFullScreenElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["webkitCurrentFullScreenElement"].get, "get webkitCurrentFullScreenElement");
box.defineProperty(Document.prototype, 'webkitFullscreenEnabled', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["webkitFullscreenEnabled"].get, "get webkitFullscreenEnabled");
box.defineProperty(Document.prototype, 'webkitFullscreenElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["webkitFullscreenElement"].get, "get webkitFullscreenElement");
box.defineProperty(Document.prototype, 'onwebkitfullscreenchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenchange"].get, "get onwebkitfullscreenchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenchange"].set, "set onwebkitfullscreenchange");
box.defineProperty(Document.prototype, 'onwebkitfullscreenerror', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenerror"].get, "get onwebkitfullscreenerror");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitfullscreenerror"].set, "set onwebkitfullscreenerror");
box.defineProperty(Document.prototype, 'rootElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["rootElement"].get, "get rootElement");
box.defineProperty(Document.prototype, 'onbeforexrselect', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforexrselect"].get, "get onbeforexrselect");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforexrselect"].set, "set onbeforexrselect");
box.defineProperty(Document.prototype, 'onabort', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onabort"].get, "get onabort");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onabort"].set, "set onabort");
box.defineProperty(Document.prototype, 'onbeforeinput', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforeinput"].get, "get onbeforeinput");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforeinput"].set, "set onbeforeinput");
box.defineProperty(Document.prototype, 'onblur', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onblur"].get, "get onblur");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onblur"].set, "set onblur");
box.defineProperty(Document.prototype, 'oncancel', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncancel"].get, "get oncancel");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncancel"].set, "set oncancel");
box.defineProperty(Document.prototype, 'oncanplay', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplay"].get, "get oncanplay");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplay"].set, "set oncanplay");
box.defineProperty(Document.prototype, 'oncanplaythrough', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplaythrough"].get, "get oncanplaythrough");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncanplaythrough"].set, "set oncanplaythrough");
box.defineProperty(Document.prototype, 'onchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onchange"].get, "get onchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onchange"].set, "set onchange");
box.defineProperty(Document.prototype, 'onclick', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onclick"].get, "get onclick");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onclick"].set, "set onclick");
box.defineProperty(Document.prototype, 'onclose', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onclose"].get, "get onclose");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onclose"].set, "set onclose");
box.defineProperty(Document.prototype, 'oncontextlost', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextlost"].get, "get oncontextlost");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextlost"].set, "set oncontextlost");
box.defineProperty(Document.prototype, 'oncontextmenu', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextmenu"].get, "get oncontextmenu");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextmenu"].set, "set oncontextmenu");
box.defineProperty(Document.prototype, 'oncontextrestored', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextrestored"].get, "get oncontextrestored");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncontextrestored"].set, "set oncontextrestored");
box.defineProperty(Document.prototype, 'oncuechange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncuechange"].get, "get oncuechange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncuechange"].set, "set oncuechange");
box.defineProperty(Document.prototype, 'ondblclick', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondblclick"].get, "get ondblclick");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondblclick"].set, "set ondblclick");
box.defineProperty(Document.prototype, 'ondrag', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondrag"].get, "get ondrag");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondrag"].set, "set ondrag");
box.defineProperty(Document.prototype, 'ondragend', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragend"].get, "get ondragend");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragend"].set, "set ondragend");
box.defineProperty(Document.prototype, 'ondragenter', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragenter"].get, "get ondragenter");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragenter"].set, "set ondragenter");
box.defineProperty(Document.prototype, 'ondragleave', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragleave"].get, "get ondragleave");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragleave"].set, "set ondragleave");
box.defineProperty(Document.prototype, 'ondragover', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragover"].get, "get ondragover");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragover"].set, "set ondragover");
box.defineProperty(Document.prototype, 'ondragstart', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragstart"].get, "get ondragstart");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondragstart"].set, "set ondragstart");
box.defineProperty(Document.prototype, 'ondrop', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondrop"].get, "get ondrop");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondrop"].set, "set ondrop");
box.defineProperty(Document.prototype, 'ondurationchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondurationchange"].get, "get ondurationchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ondurationchange"].set, "set ondurationchange");
box.defineProperty(Document.prototype, 'onemptied', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onemptied"].get, "get onemptied");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onemptied"].set, "set onemptied");
box.defineProperty(Document.prototype, 'onended', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onended"].get, "get onended");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onended"].set, "set onended");
box.defineProperty(Document.prototype, 'onerror', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onerror"].get, "get onerror");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onerror"].set, "set onerror");
box.defineProperty(Document.prototype, 'onfocus', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfocus"].get, "get onfocus");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onfocus"].set, "set onfocus");
box.defineProperty(Document.prototype, 'onformdata', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onformdata"].get, "get onformdata");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onformdata"].set, "set onformdata");
box.defineProperty(Document.prototype, 'oninput', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oninput"].get, "get oninput");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oninput"].set, "set oninput");
box.defineProperty(Document.prototype, 'oninvalid', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oninvalid"].get, "get oninvalid");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oninvalid"].set, "set oninvalid");
box.defineProperty(Document.prototype, 'onkeydown', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onkeydown"].get, "get onkeydown");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onkeydown"].set, "set onkeydown");
box.defineProperty(Document.prototype, 'onkeypress', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onkeypress"].get, "get onkeypress");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onkeypress"].set, "set onkeypress");
box.defineProperty(Document.prototype, 'onkeyup', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onkeyup"].get, "get onkeyup");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onkeyup"].set, "set onkeyup");
box.defineProperty(Document.prototype, 'onload', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onload"].get, "get onload");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onload"].set, "set onload");
box.defineProperty(Document.prototype, 'onloadeddata', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onloadeddata"].get, "get onloadeddata");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onloadeddata"].set, "set onloadeddata");
box.defineProperty(Document.prototype, 'onloadedmetadata', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onloadedmetadata"].get, "get onloadedmetadata");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onloadedmetadata"].set, "set onloadedmetadata");
box.defineProperty(Document.prototype, 'onloadstart', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onloadstart"].get, "get onloadstart");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onloadstart"].set, "set onloadstart");
box.defineProperty(Document.prototype, 'onmousedown', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmousedown"].get, "get onmousedown");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmousedown"].set, "set onmousedown");
box.defineProperty(Document.prototype, 'onmouseenter', undefined, true, true, undefined, function () {debugger; return 'undefined'}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseenter"].get, "get onmouseenter");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseenter"].set, "set onmouseenter");
box.defineProperty(Document.prototype, 'onmouseleave', undefined, true, true, undefined, function () {debugger; return 'undefined'}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseleave"].get, "get onmouseleave");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseleave"].set, "set onmouseleave");
box.defineProperty(Document.prototype, 'onmousemove', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmousemove"].get, "get onmousemove");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmousemove"].set, "set onmousemove");
box.defineProperty(Document.prototype, 'onmouseout', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseout"].get, "get onmouseout");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseout"].set, "set onmouseout");
box.defineProperty(Document.prototype, 'onmouseover', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseover"].get, "get onmouseover");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseover"].set, "set onmouseover");
box.defineProperty(Document.prototype, 'onmouseup', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseup"].get, "get onmouseup");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmouseup"].set, "set onmouseup");
box.defineProperty(Document.prototype, 'onmousewheel', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmousewheel"].get, "get onmousewheel");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onmousewheel"].set, "set onmousewheel");
box.defineProperty(Document.prototype, 'onpause', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpause"].get, "get onpause");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpause"].set, "set onpause");
box.defineProperty(Document.prototype, 'onplay', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onplay"].get, "get onplay");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onplay"].set, "set onplay");
box.defineProperty(Document.prototype, 'onplaying', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onplaying"].get, "get onplaying");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onplaying"].set, "set onplaying");
box.defineProperty(Document.prototype, 'onprogress', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onprogress"].get, "get onprogress");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onprogress"].set, "set onprogress");
box.defineProperty(Document.prototype, 'onratechange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onratechange"].get, "get onratechange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onratechange"].set, "set onratechange");
box.defineProperty(Document.prototype, 'onreset', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onreset"].get, "get onreset");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onreset"].set, "set onreset");
box.defineProperty(Document.prototype, 'onresize', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onresize"].get, "get onresize");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onresize"].set, "set onresize");
box.defineProperty(Document.prototype, 'onscroll', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onscroll"].get, "get onscroll");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onscroll"].set, "set onscroll");
box.defineProperty(Document.prototype, 'onsecuritypolicyviolation', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsecuritypolicyviolation"].get, "get onsecuritypolicyviolation");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsecuritypolicyviolation"].set, "set onsecuritypolicyviolation");
box.defineProperty(Document.prototype, 'onseeked', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onseeked"].get, "get onseeked");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onseeked"].set, "set onseeked");
box.defineProperty(Document.prototype, 'onseeking', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onseeking"].get, "get onseeking");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onseeking"].set, "set onseeking");
box.defineProperty(Document.prototype, 'onselect', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onselect"].get, "get onselect");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onselect"].set, "set onselect");
box.defineProperty(Document.prototype, 'onslotchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onslotchange"].get, "get onslotchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onslotchange"].set, "set onslotchange");
box.defineProperty(Document.prototype, 'onstalled', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onstalled"].get, "get onstalled");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onstalled"].set, "set onstalled");
box.defineProperty(Document.prototype, 'onsubmit', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsubmit"].get, "get onsubmit");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsubmit"].set, "set onsubmit");
box.defineProperty(Document.prototype, 'onsuspend', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsuspend"].get, "get onsuspend");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onsuspend"].set, "set onsuspend");
box.defineProperty(Document.prototype, 'ontimeupdate', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontimeupdate"].get, "get ontimeupdate");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontimeupdate"].set, "set ontimeupdate");
box.defineProperty(Document.prototype, 'ontoggle', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontoggle"].get, "get ontoggle");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontoggle"].set, "set ontoggle");
box.defineProperty(Document.prototype, 'onvolumechange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onvolumechange"].get, "get onvolumechange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onvolumechange"].set, "set onvolumechange");
box.defineProperty(Document.prototype, 'onwaiting', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwaiting"].get, "get onwaiting");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwaiting"].set, "set onwaiting");
box.defineProperty(Document.prototype, 'onwebkitanimationend', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationend"].get, "get onwebkitanimationend");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationend"].set, "set onwebkitanimationend");
box.defineProperty(Document.prototype, 'onwebkitanimationiteration', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationiteration"].get, "get onwebkitanimationiteration");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationiteration"].set, "set onwebkitanimationiteration");
box.defineProperty(Document.prototype, 'onwebkitanimationstart', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationstart"].get, "get onwebkitanimationstart");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkitanimationstart"].set, "set onwebkitanimationstart");
box.defineProperty(Document.prototype, 'onwebkittransitionend', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkittransitionend"].get, "get onwebkittransitionend");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwebkittransitionend"].set, "set onwebkittransitionend");
box.defineProperty(Document.prototype, 'onwheel', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwheel"].get, "get onwheel");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onwheel"].set, "set onwheel");
box.defineProperty(Document.prototype, 'onauxclick', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onauxclick"].get, "get onauxclick");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onauxclick"].set, "set onauxclick");
box.defineProperty(Document.prototype, 'ongotpointercapture', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ongotpointercapture"].get, "get ongotpointercapture");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ongotpointercapture"].set, "set ongotpointercapture");
box.defineProperty(Document.prototype, 'onlostpointercapture', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onlostpointercapture"].get, "get onlostpointercapture");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onlostpointercapture"].set, "set onlostpointercapture");
box.defineProperty(Document.prototype, 'onpointerdown', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerdown"].get, "get onpointerdown");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerdown"].set, "set onpointerdown");
box.defineProperty(Document.prototype, 'onpointermove', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointermove"].get, "get onpointermove");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointermove"].set, "set onpointermove");
box.defineProperty(Document.prototype, 'onpointerrawupdate', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerrawupdate"].get, "get onpointerrawupdate");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerrawupdate"].set, "set onpointerrawupdate");
box.defineProperty(Document.prototype, 'onpointerup', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerup"].get, "get onpointerup");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerup"].set, "set onpointerup");
box.defineProperty(Document.prototype, 'onpointercancel', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointercancel"].get, "get onpointercancel");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointercancel"].set, "set onpointercancel");
box.defineProperty(Document.prototype, 'onpointerover', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerover"].get, "get onpointerover");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerover"].set, "set onpointerover");
box.defineProperty(Document.prototype, 'onpointerout', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerout"].get, "get onpointerout");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerout"].set, "set onpointerout");
box.defineProperty(Document.prototype, 'onpointerenter', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerenter"].get, "get onpointerenter");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerenter"].set, "set onpointerenter");
box.defineProperty(Document.prototype, 'onpointerleave', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerleave"].get, "get onpointerleave");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpointerleave"].set, "set onpointerleave");
box.defineProperty(Document.prototype, 'onselectstart', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onselectstart"].get, "get onselectstart");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onselectstart"].set, "set onselectstart");
box.defineProperty(Document.prototype, 'onselectionchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onselectionchange"].get, "get onselectionchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onselectionchange"].set, "set onselectionchange");
box.defineProperty(Document.prototype, 'onanimationend', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationend"].get, "get onanimationend");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationend"].set, "set onanimationend");
box.defineProperty(Document.prototype, 'onanimationiteration', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationiteration"].get, "get onanimationiteration");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationiteration"].set, "set onanimationiteration");
box.defineProperty(Document.prototype, 'onanimationstart', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationstart"].get, "get onanimationstart");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onanimationstart"].set, "set onanimationstart");
box.defineProperty(Document.prototype, 'ontransitionrun', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionrun"].get, "get ontransitionrun");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionrun"].set, "set ontransitionrun");
box.defineProperty(Document.prototype, 'ontransitionstart', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionstart"].get, "get ontransitionstart");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionstart"].set, "set ontransitionstart");
box.defineProperty(Document.prototype, 'ontransitionend', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionend"].get, "get ontransitionend");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitionend"].set, "set ontransitionend");
box.defineProperty(Document.prototype, 'ontransitioncancel', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitioncancel"].get, "get ontransitioncancel");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["ontransitioncancel"].set, "set ontransitioncancel");
box.defineProperty(Document.prototype, 'oncopy', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncopy"].get, "get oncopy");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncopy"].set, "set oncopy");
box.defineProperty(Document.prototype, 'oncut', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncut"].get, "get oncut");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["oncut"].set, "set oncut");
box.defineProperty(Document.prototype, 'onpaste', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpaste"].get, "get onpaste");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onpaste"].set, "set onpaste");
box.defineProperty(Document.prototype, 'children', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["children"].get, "get children");
box.defineProperty(Document.prototype, 'firstElementChild', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["firstElementChild"].get, "get firstElementChild");
box.defineProperty(Document.prototype, 'lastElementChild', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["lastElementChild"].get, "get lastElementChild");
box.defineProperty(Document.prototype, 'childElementCount', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["childElementCount"].get, "get childElementCount");
box.defineProperty(Document.prototype, 'activeElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["activeElement"].get, "get activeElement");
box.defineProperty(Document.prototype, 'styleSheets', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["styleSheets"].get, "get styleSheets");
box.defineProperty(Document.prototype, 'pointerLockElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["pointerLockElement"].get, "get pointerLockElement");
box.defineProperty(Document.prototype, 'fullscreenElement', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenElement"].get, "get fullscreenElement");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fullscreenElement"].set, "set fullscreenElement");
box.defineProperty(Document.prototype, 'adoptedStyleSheets', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["adoptedStyleSheets"].get, "get adoptedStyleSheets");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["adoptedStyleSheets"].set, "set adoptedStyleSheets");
box.defineProperty(Document.prototype, 'fonts', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fonts"].get, "get fonts");
box.defineProperty(Document.prototype, 'adoptNode', function adoptNode(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.adoptNode)
box.defineProperty(Document.prototype, 'append', function append(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.append)
box.defineProperty(Document.prototype, 'captureEvents', function captureEvents(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.captureEvents)
box.defineProperty(Document.prototype, 'caretRangeFromPoint', function caretRangeFromPoint(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.caretRangeFromPoint)
box.defineProperty(Document.prototype, 'clear', function clear(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.clear)
box.defineProperty(Document.prototype, 'close', function close(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.close)
box.defineProperty(Document.prototype, 'createAttribute', function createAttribute(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createAttribute)
box.defineProperty(Document.prototype, 'createAttributeNS', function createAttributeNS(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createAttributeNS)
box.defineProperty(Document.prototype, 'createCDATASection', function createCDATASection(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createCDATASection)
box.defineProperty(Document.prototype, 'createComment', function createComment(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createComment)
box.defineProperty(Document.prototype, 'createDocumentFragment', function createDocumentFragment(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createDocumentFragment)
box.defineProperty(Document.prototype, 'createElement', function createElement(){
    let element = {}
    if (arguments[0] === 'canvas') {
        Object.setPrototypeOf(element, HTMLCanvasElement.prototype)
        return box.proxy(element, 'document_createElement_canvas')
    }
    debugger;
}, true, true, true); box.func_set_fake_toString(Document.prototype.createElement)
box.defineProperty(Document.prototype, 'createElementNS', function createElementNS(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createElementNS)
box.defineProperty(Document.prototype, 'createEvent', function createEvent(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createEvent)
box.defineProperty(Document.prototype, 'createExpression', function createExpression(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createExpression)
box.defineProperty(Document.prototype, 'createNSResolver', function createNSResolver(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createNSResolver)
box.defineProperty(Document.prototype, 'createNodeIterator', function createNodeIterator(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createNodeIterator)
box.defineProperty(Document.prototype, 'createProcessingInstruction', function createProcessingInstruction(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createProcessingInstruction)
box.defineProperty(Document.prototype, 'createRange', function createRange(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createRange)
box.defineProperty(Document.prototype, 'createTextNode', function createTextNode(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createTextNode)
box.defineProperty(Document.prototype, 'createTreeWalker', function createTreeWalker(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.createTreeWalker)
box.defineProperty(Document.prototype, 'elementFromPoint', function elementFromPoint(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.elementFromPoint)
box.defineProperty(Document.prototype, 'elementsFromPoint', function elementsFromPoint(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.elementsFromPoint)
box.defineProperty(Document.prototype, 'evaluate', function evaluate(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.evaluate)
box.defineProperty(Document.prototype, 'execCommand', function execCommand(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.execCommand)
box.defineProperty(Document.prototype, 'exitFullscreen', function exitFullscreen(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.exitFullscreen)
box.defineProperty(Document.prototype, 'exitPointerLock', function exitPointerLock(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.exitPointerLock)
box.defineProperty(Document.prototype, 'getElementById', function getElementById(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.getElementById)
box.defineProperty(Document.prototype, 'getElementsByClassName', function getElementsByClassName(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.getElementsByClassName)
box.defineProperty(Document.prototype, 'getElementsByName', function getElementsByName(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.getElementsByName)
box.defineProperty(Document.prototype, 'getElementsByTagName', function getElementsByTagName(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.getElementsByTagName)
box.defineProperty(Document.prototype, 'getElementsByTagNameNS', function getElementsByTagNameNS(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.getElementsByTagNameNS)
box.defineProperty(Document.prototype, 'getSelection', function getSelection(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.getSelection)
box.defineProperty(Document.prototype, 'hasFocus', function hasFocus(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.hasFocus)
box.defineProperty(Document.prototype, 'importNode', function importNode(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.importNode)
box.defineProperty(Document.prototype, 'open', function open(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.open)
box.defineProperty(Document.prototype, 'prepend', function prepend(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.prepend)
box.defineProperty(Document.prototype, 'queryCommandEnabled', function queryCommandEnabled(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.queryCommandEnabled)
box.defineProperty(Document.prototype, 'queryCommandIndeterm', function queryCommandIndeterm(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.queryCommandIndeterm)
box.defineProperty(Document.prototype, 'queryCommandState', function queryCommandState(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.queryCommandState)
box.defineProperty(Document.prototype, 'queryCommandSupported', function queryCommandSupported(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.queryCommandSupported)
box.defineProperty(Document.prototype, 'queryCommandValue', function queryCommandValue(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.queryCommandValue)
box.defineProperty(Document.prototype, 'querySelector', function querySelector(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.querySelector)
box.defineProperty(Document.prototype, 'querySelectorAll', function querySelectorAll(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.querySelectorAll)
box.defineProperty(Document.prototype, 'releaseEvents', function releaseEvents(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.releaseEvents)
box.defineProperty(Document.prototype, 'replaceChildren', function replaceChildren(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.replaceChildren)
box.defineProperty(Document.prototype, 'webkitCancelFullScreen', function webkitCancelFullScreen(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.webkitCancelFullScreen)
box.defineProperty(Document.prototype, 'webkitExitFullscreen', function webkitExitFullscreen(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.webkitExitFullscreen)
box.defineProperty(Document.prototype, 'write', function write(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.write)
box.defineProperty(Document.prototype, 'writeln', function writeln(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.writeln)

box.defineProperty(Document.prototype, 'prerendering', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["prerendering"].get, "get prerendering");
box.defineProperty(Document.prototype, 'onprerenderingchange', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onprerenderingchange"].get, "get onprerenderingchange");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onprerenderingchange"].set, "set onprerenderingchange");
box.defineProperty(Document.prototype, 'fragmentDirective', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["fragmentDirective"].get, "get fragmentDirective");
box.defineProperty(Document.prototype, 'onbeforematch', undefined, true, true, undefined, function () {debugger}, function (value) {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforematch"].get, "get onbeforematch");box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["onbeforematch"].set, "set onbeforematch");
box.defineProperty(Document.prototype, 'timeline', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["timeline"].get, "get timeline");
box.defineProperty(Document.prototype, 'pictureInPictureEnabled', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["pictureInPictureEnabled"].get, "get pictureInPictureEnabled");
box.defineProperty(Document.prototype, 'pictureInPictureElement', undefined, true, true, undefined, function () {debugger});box.func_set_fake_toString(Object.getOwnPropertyDescriptors(Document.prototype)["pictureInPictureElement"].get, "get pictureInPictureElement");
box.defineProperty(Document.prototype, 'exitPictureInPicture', function exitPictureInPicture(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.exitPictureInPicture)
box.defineProperty(Document.prototype, 'getAnimations', function getAnimations(){debugger;}, true, true, true); box.func_set_fake_toString(Document.prototype.getAnimations)

